name: 'lint'
on:
  pull_request:
    paths:
      - 'xo-install.sh'
      - 'xo-vm-import.sh'
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run shellcheck
      uses: ludeeus/action-shellcheck@2.0.0

    - name: run shfmt
      uses: luizm/action-sh-checker@v0.9.0
      env:
        SHFMT_OPTS: -d
      with:
        sh_checker_comment: false
        sh_checker_shellcheck_disable: true
